/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeniorRouteImport } from './routes/senior'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeniorRoute = SeniorRouteImport.update({
  id: '/senior',
  path: '/senior',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/provider': typeof ProviderRoute
  '/search': typeof SearchRoute
  '/senior': typeof SeniorRoute
  '/book/$id': typeof BookIdRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$id': typeof SIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/provider': typeof ProviderRoute
  '/search': typeof SearchRoute
  '/senior': typeof SeniorRoute
  '/book/$id': typeof BookIdRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$id': typeof SIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/provider': typeof ProviderRoute
  '/search': typeof SearchRoute
  '/senior': typeof SeniorRoute
  '/book/$id': typeof BookIdRoute
  '/c/$slug': typeof CSlugRoute
  '/s/$id': typeof SIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/cart'
    | '/custom'
    | '/login'
    | '/plans'
    | '/provider'
    | '/search'
    | '/senior'
    | '/book/$id'
    | '/c/$slug'
    | '/s/$id'
    | '/shop/$id'
    | '/track/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/cart'
    | '/custom'
    | '/login'
    | '/plans'
    | '/provider'
    | '/search'
    | '/senior'
    | '/book/$id'
    | '/c/$slug'
    | '/s/$id'
    | '/shop/$id'
    | '/track/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/cart'
    | '/custom'
    | '/login'
    | '/plans'
    | '/provider'
    | '/search'
    | '/senior'
    | '/book/$id'
    | '/c/$slug'
    | '/s/$id'
    | '/shop/$id'
    | '/track/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  CartRoute: typeof CartRoute
  CustomRoute: typeof CustomRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  ProviderRoute: typeof ProviderRoute
  SearchRoute: typeof SearchRoute
  SeniorRoute: typeof SeniorRoute
  BookIdRoute: typeof BookIdRoute
  CSlugRoute: typeof CSlugRoute
  SIdRoute: typeof SIdRoute
  ShopIdRoute: typeof ShopIdRoute
  TrackIdRoute: typeof TrackIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senior': {
      id: '/senior'
      path: '/senior'
      fullPath: '/senior'
      preLoaderRoute: typeof SeniorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  CartRoute: CartRoute,
  CustomRoute: CustomRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  ProviderRoute: ProviderRoute,
  SearchRoute: SearchRoute,
  SeniorRoute: SeniorRoute,
  BookIdRoute: BookIdRoute,
  CSlugRoute: CSlugRoute,
  SIdRoute: SIdRoute,
  ShopIdRoute: ShopIdRoute,
  TrackIdRoute: TrackIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
